# Generated by Django 5.2.5 on 2025-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('animation', 'Animation'), ('documentary', 'Documentary')], default=0),
            preserve_default=False,
        ),
    ]
