# Generated by Django 5.2.5 on 2025-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_genre_delete_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('Drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('animation', 'Animation'), ('documentary', 'Documentary')]),
        ),
    ]
