# Generated by Django 5.2.5 on 2025-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('animation', 'Animation'), ('documentary', 'Documentary')]),
        ),
    ]
