# Generated by Django 5.2.5 on 2025-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Sci_fi', 'Science Fiction'), ('Romance', 'Romance'), ('Animation', 'Animation'), ('Documentary', 'Documentary')]),
        ),
    ]
